const stories=[{name:'My Story',tag:'A LIFE WORTH SINGING',title:'Every chapter counts.',desc:'Your roots, your comeback, your next great chapter.',image:0,moods:['Life journey','Hometown roots','Comeback','Celebration','Surprise me'],caption:'Sample caption: “First studio. Same dream I had at sixteen.”',lyric:'Sixteen-year-old dreams in a room of my own, / Every color on these walls says I made it home.'},{name:'Funny',tag:'A LITTLE LOVE. A LITTLE ROAST.',title:'The legend lives on.',desc:'That one friend. That one story. That unforgettable chorus.',image:1,moods:['Playful roast','Inside jokes','Birthday chaos','Surprise me'],caption:'Sample caption: “The cake collapsed. Our confidence did not.”',lyric:'You called it a masterpiece, we called the floor, / Best worst birthday we keep coming back for.'},{name:'Couples',tag:'YOUR VERY OWN LOVE SONG',title:'Our kind of forever.',desc:'From the first hello to the kitchen slow dance.',image:2,moods:['In love','Crush','Missing you','Breakup','Anniversary','Surprise me'],caption:'Sample caption: “No reservations. Just our kitchen and this song.”',lyric:'We never needed chandeliers to make the evening shine, / Just your hand in mine and a little borrowed time.'},{name:'Friendship',tag:'FOR YOUR FAVORITE PEOPLE',title:'Wrong turn. Right people.',desc:'The road trips, the laughter, the partners in crime.',image:3,moods:['Best friends','Partners in crime','Funny','Flirty','Falling out','Surprise me'],caption:'Sample caption: “Missed the exit. Found our favorite day.”',lyric:'We lost the map but found our way, / You’re the people I would choose on any day.'}];
const rawStories=[
{title:'Still here. Still building.',tag:'MY STORY / THE UNEDITED VERSION',desc:'The late shifts, second chances, and things you built yourself.',caption:'Fictional caption: “45. First shop with my name on the door.”',comment:'Fictional comment: “Still wearing the boots from your first job.”',lyric:'Same old boots on a brand-new floor, / Forty-five years brought me to this door.'},
{title:'He said he’d help.',tag:'FUNNY / A REGULAR SATURDAY',desc:'Ten minutes into gardening. He’s supervising.',caption:'Fictional caption: “He said he’d help.”',comment:'Fictional comment: “Hasn’t moved a single plant.”',lyric:'You came to move the garden, took the wheelbarrow seat, / Now I’m doing all the digging while you put up your feet.'},
{title:'Spin cycle soulmates.',tag:'COUPLES / LOVE, WITH EXTRA NOODLES',desc:'No grand gestures. Just you, me, and dryer number three.',caption:'Fictional caption: “Date night. Two washes and extra noodles.”',comment:'Fictional comment: “You still owe me the last dumpling.”',lyric:'Two washes, extra noodles, one sock gone astray, / I’d choose you in this laundromat on any given day.'},
{title:'He knows the regulars.',tag:'FRIENDSHIP / EVERYONE’S FAVORITE',desc:'We came to see our friends. They came to see the dog.',caption:'Fictional caption: “Pretty sure we’re just his ride home.”',comment:'Fictional comment: “He gets greeted before we do.”',lyric:'They shout your name before they ask for mine, / Green bandana, pink tongue, stealing all the limelight.'}
];

stories.forEach((s,i)=>Object.assign(s,rawStories[i]));
// Attach licensed 30-second demo files here when produced. Null keeps the honest unavailable state.
const samples=[{genre:'Acoustic / Folk',voice:'Female',src:null},{genre:'Country',voice:'Male',src:null},{genre:'R&B / Soul',voice:'Female',src:null},{genre:'Indie Pop',voice:'Male',src:null}];
function sample(i){const x=samples[i];return `<div class="song-sample"><span class="sample-label">${x.genre} · ${x.voice} vocals</span><p class="sample-lyric">${stories[i].lyric.replace(' / ','<br>')}</p>${x.src?`<audio controls preload="none" aria-label="30-second ${stories[i].name} song sample" src="${x.src}"></audio>`:`<button class="sample-pending" disabled aria-label="30-second sample not recorded yet">▶ &nbsp; 30-second sample · Coming soon</button>`}</div>`}
let current=0,activeStory=1;
const $=s=>document.querySelector(s);
const builder=$('#builder');
function photo(i){return `<div role="img" aria-label="${['Fictional woman in her workshop','Fictional casually dressed adult couple joking with a wheelbarrow in their backyard','Fictional couple sharing noodles at a laundromat','Altered illustrative photo of two men and a black-and-white dog at a bar'][i]}" class="photo q${i}"></div>`}
const mayaPosts=[
{title:'New apartment',likes:'1,284',caption:'Moved out. Took <mark>the plant Mum said I’d kill</mark>.'},
{title:'First 5K',likes:'2,106',caption:'Ran a 5K. <mark>Complained for 4.9 of it.</mark>'},
{title:'Baking era',likes:'938',caption:'Cake collapsed. <mark>Confidence remains unreasonable.</mark>'},
{title:'Friday dinner',likes:'1,762',caption:'Dressed up to <mark>split one plate of fries</mark>.'},
{title:'Morning routine',likes:'1,403',caption:'Bought a yoga mat. <mark>The dog owns it now.</mark>'},
{title:'Twenty-five',likes:'2,341',caption:'25. <mark>Still calling Mum about laundry.</mark>'}
];
const mayaDemo={title:'Unreasonably Confident',genre:'Indie pop',voice:'Female',src:null,lyric:'Five K done, complained through most, / Burnt the cake but here’s my toast: / Twenty-five, still figuring it out, / Got a dog on my yoga mat and a life to laugh about.'};
function mayaPlayer(){return `<div class="maya-player"><span class="eyebrow">YOUR POSTS → YOUR CHORUS</span><h3>${mayaDemo.title}</h3><p class="small">${mayaDemo.genre} · ${mayaDemo.voice} vocals · Biography demo</p><blockquote>${mayaDemo.lyric.replaceAll(' / ','<br>')}</blockquote>${mayaDemo.src?`<audio controls preload="none" src="${mayaDemo.src}" aria-label="Maya’s 30-second biography song sample"></audio>`:'<button class="sample-pending" disabled>▶ &nbsp; 30-second song demo · Recording pending</button>'}</div>`}
function render(){document.body.dataset.design='0';
$('#site').innerHTML=`<nav><a class="brand" href="#" aria-label="AnthemSmith home"><span class="brand-icon"><img src="assets/anthemsmith-logo.png" alt=""></span><span class="brand-name">🎶 AnthemSmith🎵🔨</span></a><div class="nav-links"><a href="#stories">The stories</a><a href="#how">How it works</a><button class="nav-button" data-create="0">Make a song</button></div></nav>
<section class="hero narrative-hero"><div class="copy"><span class="eyebrow">ANTHEMSMITH · YOUR VIBE, FORGED INTO A SONG</span><h1>A picture is worth<br>a thousand words.<br><em>Your Instagram<br>is worth a song.</em></h1><p class="intro">The nights worth remembering. The people you’ll never forget. A personal song made from the stories between your posts.</p><button class="primary" data-create="0">Make my song — $5</button><a class="explore" href="#stories">Find your kind of story ↓</a><p class="small">One original song. 3–4 minutes. All you.</p></div><section class="maya-profile" aria-label="Fictional Instagram biography example"><header><div><b>Maya, 25</b><span>@maya.aftercoffee · Fictional profile</span></div><span class="demo-label">DEMO</span></header><p class="profile-bio">new city · old friends · questionable baking</p><p class="profile-disclosure">Illustrative posts and like counts — not customer reviews.</p><div class="maya-grid">${mayaPosts.map((p,i)=>`<article class="maya-post"><div class="maya-photo m${i}" role="img" aria-label="Fictional Maya: ${p.title}"></div><div class="maya-caption"><span class="likes">♡ ${p.likes} likes</span><p>${p.caption}</p></div></article>`).join('')}</div>${mayaPlayer()}</section></section>
<section class="story-intro" id="stories"><span class="eyebrow">EVERYONE HAS ONE.</span><h2>What’s your anthem?</h2><p>A love letter. A little roast. A whole life in a chorus.</p></section>
<section class="story-grid" aria-label="Four kinds of songs">${stories.map((s,i)=>`<article class="story-card"><button class="photo-button" data-demo="${i}" aria-label="Explore ${s.name}">${photo(i)}</button><div class="story-body"><span class="eyebrow">0${i+1} / ${s.name}</span><h3>${s.title}</h3><p>${s.desc}</p>${sample(i)}<button class="text-button story-cta" data-create="${i}">${['Tell my story','Roast my friend','Make our love song','Make our anthem'][i]} ↗</button></div></article>`).join('')}</section><p class="example-note">Fictional stories and sample lyrics. Audio demos coming soon.</p>
<section class="how-story" id="how"><div class="how-copy"><span class="eyebrow">MORE THAN A SINGLE PHOTO</span><h2>We find the story<br>between the posts.</h2><p>The photos set the scene. Your captions tell us what happened. The comments? That’s where your people fill in the good bits.</p><p>Share the moments you want included, across your profile. Together, they become a song that feels like you.</p></div><div class="lyric-recipe"><span class="eyebrow">FROM A POST TO A CHORUS · FICTIONAL EXAMPLE</span><div class="recipe-line"><span>THE CAPTION</span><p>“45. First shop with my name on the door.”</p></div><div class="recipe-line"><span>THE COMMENT</span><p>“Still wearing the boots from your first job.”</p></div><div class="recipe-song"><span>THE SONG</span><blockquote>Same old boots on a brand-new floor,<br>Forty-five years brought me to this door.</blockquote><small>Acoustic / Folk · Female vocals</small></div></div></section>
<div id="soundSlot"></div>
<section class="private-story"><div><span class="eyebrow">PRIVATE ACCOUNT? YOU’RE INVITED.</span><h2>Let us into your world.</h2><p>Follow @AnthemSmith and message “SONG.” Our team requests to follow you back; approve it if prompted. Or paste the captions and comments you want included in your brief.</p></div><a class="instagram-button" href="https://www.instagram.com/anthemsmith/" target="_blank" rel="noopener">Find @AnthemSmith ↗</a></section>
<section class="closing"><span class="eyebrow">FOR YOU. FOR THEM. FOR THE GROUP CHAT.</span><h2>The soundtrack to your story.</h2><button class="primary" data-create="0">Make it yours — $5</button></section><footer><a class="brand" href="#"><span class="brand-icon"><img src="assets/anthemsmith-logo.png" alt=""></span><span class="brand-name">🎶 AnthemSmith🎵🔨</span></a><span>Design preview · No orders, follow requests, or songs are sent automatically.</span></footer>`;$('#soundSlot').replaceWith(builder)}
function moods(){const s=stories.find(s=>s.name===$('#categorySelect').value);$('#moodSelect').innerHTML=s.moods.map(x=>`<option>${x}</option>`).join('')}
function openBuilder(i){$('#demo').close();$('#songForm').hidden=false;$('#brief').hidden=true;$('#categorySelect').value=stories[i].name;moods();builder.scrollIntoView({behavior:'smooth',block:'start'})}
document.addEventListener('click',e=>{let b=e.target.closest('[data-design]');if(b){render(+b.dataset.design);return}b=e.target.closest('[data-story]');if(b){activeStory=+b.dataset.story;render(current);return}b=e.target.closest('[data-create]');if(b){openBuilder(+b.dataset.create);return}b=e.target.closest('[data-demo]');if(b){activeStory=+b.dataset.demo;const s=stories[activeStory];$('#demoTitle').textContent=s.title;$('#demoPhoto').className='photo q'+s.image;$('#demoCaption').textContent=s.caption;$('#demoSample').innerHTML=sample(+b.dataset.demo);$('#demo').showModal()}if(e.target.closest('.close'))e.target.closest('dialog').close()});
$('#demoCreate').onclick=()=>openBuilder(activeStory);$('#categorySelect').onchange=moods;
$('#referenceUrl').addEventListener('input',e=>{const field=e.target;field.setCustomValidity('');if(!field.value.trim())return;try{const u=new URL(field.value);const host=u.hostname.toLowerCase();if(u.protocol!=='https:'||!['youtube.com','www.youtube.com','m.youtube.com','music.youtube.com','youtu.be','open.spotify.com','spotify.link'].includes(host))field.setCustomValidity('Paste an HTTPS YouTube or Spotify song link.')}catch{field.setCustomValidity('Paste a complete YouTube or Spotify link.')}});
$('#songForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),brief=$('#brief');brief.replaceChildren();const h=document.createElement('h3');h.textContent='Your song brief';brief.append(h);for(const [k,label] of Object.entries({names:'About',category:'Story',mood:'Mood',instagram1:'Instagram',instagram2:'Second Instagram',referenceUrl:'Favorite song link',details:'Details',artist:'Reference artist',song:'Reference song',voice:'Vocals',genre:'Genre'})){if(!data.get(k))continue;const p=document.createElement('p');p.textContent=label+': '+data.get(k);brief.append(p)}const note=document.createElement('p');note.className='small';note.textContent='Preview only. Nothing was sent or saved; no payment was taken.';brief.append(note);const back=document.createElement('button');back.className='primary';back.textContent='Edit brief';back.onclick=()=>{brief.hidden=true;e.target.hidden=false};brief.append(back);e.target.hidden=true;brief.hidden=false};
render();moods();

$('#addProfile').onclick=()=>{const open=$('#secondProfile').hidden;$('#secondProfile').hidden=!open;$('#instagram2').disabled=!open;$('#addProfile').textContent=open?'− Remove second Instagram':'+ Add a second Instagram';if(open)$('#instagram2').focus()};
for(const selector of ['#instagram1','#instagram2']){$(selector).addEventListener('input',e=>{const f=e.target;f.setCustomValidity('');if(!f.value.trim())return;try{const u=new URL(f.value);if(u.protocol!=='https:'||!['instagram.com','www.instagram.com'].includes(u.hostname.toLowerCase())||u.pathname==='/'||/^\/(p|reel|reels|stories)\//.test(u.pathname))f.setCustomValidity('Paste an Instagram profile URL, not a post link.')}catch{f.setCustomValidity('Paste a complete Instagram profile URL.')}})}
